In [8]:
import pandas as pd
import numpy as np
import selenium
from selenium import webdriver
import time
from selenium.common.exceptions import NoSuchElementException, TimeoutException, ElementNotInteractableException
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

In [18]:
driver=webdriver.Chrome("chromedriver.exe")#opening the chrome driver

In [22]:
driver.get('https://flight.easemytrip.com/FlightList/Index?srch=BLR-Bangalore-India|DEL-Delhi-India|03/02/2022&px=1-0-0&cbn=0&ar=undefined&isow=true&isdm=true&lng=&&IsDoubleSeat=false')



time.sleep(3)

In [23]:

Airline =[]
Dep_time =[]
Arr_time =[]
Durtion =[]
Route =[]
Source =[]
Destination =[]
Stops =[]
Price =[]
Date =[]

In [24]:
for i in range(45):
    heading =driver.find_element_by_xpath('//*[@id="jssor_1"]/div/div/div/div/div[2]/div[7]/div[1]/div[1]/div[1]')
    heading.click()
    time.sleep(6)
    
    

    #Airline
    for i in driver.find_elements_by_xpath("//*[@id='ResultDiv']/div/div/div/div/div/div/div/div/div/span[1]"):
        Airline.append(i.text)


    #departure time
    for i in driver.find_elements_by_xpath('//*[@id="ResultDiv"]/div/div/div/div/div/div/div[2]/span[1]'):
        Dep_time.append(i.text)



    #arrival time
    for i in driver.find_elements_by_xpath('//*[@id="ResultDiv"]/div/div/div/div/div/div/div[4]/span[1]'):
        Arr_time.append(i.text)


    #duration in hours
    for i in driver.find_elements_by_xpath('//*[@id="ResultDiv"]/div/div/div/div/div/div/div[3]/span[1]'):
        Durtion.append(i.text)


    #route 
    count=0

    for i in driver.find_elements_by_xpath('//*[@id="ResultDiv"]/div/div/div/div/div/div/div[3]/span[2]'):
        Stops.append(i.text)
        detail =driver.find_element_by_xpath(f"//*[@id='{count}']")
        detail.click()
        route1 =driver.find_element_by_xpath(f'//*[@id="fd{count}"]/div/div[2]/div[1]/span[1]/span[1]')
        route2 =driver.find_element_by_xpath(f'//*[@id="fd{count}"]/div/div[2]/div[1]/span[1]/span[2]')
        """try:
            route3 =driver.find_element_by_xpath(f'//*[@id="fd{count}"]/div/div[2]/div[2]/span[1]/span[2]')
        except:
            break"""

        str1 = '--->'

        via =route1.text + str1
        route4= via + route2.text
        # route5 =route4 + str1 
        # route6 =route5 + route3.text
        Route.append(route4)


        count +=1

    #source
    for i in driver.find_elements_by_xpath('//*[@id="ResultDiv"]/div/div/div/div/div/div[1]/div[2]/span[2]'):
        Source.append(i.text)
    #destination
    for i in driver.find_elements_by_xpath('//*[@id="ResultDiv"]/div/div/div/div/div/div/div[4]/span[2]'):
        Destination.append(i.text)
    #price    
    for i in driver.find_elements_by_xpath('//*[@class="col-md-8 col-sm-8 col-xs-9 txt-r6-n ng-binding"]'):
        Price.append(i.text)
    #date
    i  = driver.find_elements_by_xpath('//*[@class="col-md-8 col-sm-8 col-xs-9 txt-r6-n ng-binding"]')
    for j in i:
        date1 =driver.find_element_by_xpath('//*[@id="jssor_1"]/div/div/div/div/div[2]/div[6]/div[1]/div[1]/div[1]') 
        Date.append(date1.text)

In [25]:
len(Airline) ,len(Dep_time),len(Arr_time),len(Durtion ),len(Route ),len(Source ),len(Destination),len(Stops),len(Price),len(Date)

(8962, 8962, 8962, 8962, 8962, 8962, 8962, 8962, 15311, 15311)

In [26]:
 df = pd.DataFrame({"Date":Date[0:8962],
                      "Airline" : Airline,
                     "Source":Source,
                     "Destination":Destination,
                       "Dep_time" : Dep_time,
                       "Arr_time" : Arr_time,
                       "Durtion" : Durtion,
                        "Route":Route,
                         "stop": Stops,
                       "price": Price[0:8962]
                       })

In [27]:
df

,Date,Airline,Source,Destination,Dep_time,Arr_time,Durtion,Route,stop,price
0,Feb 04,GO FIRST,Bangalore,Delhi,07:20,10:10,02h 50m,BLR--->DEL,non-stop,"7,487"
1,Feb 04,GO FIRST,Bangalore,Delhi,20:55,23:50,02h 55m,BLR--->DEL,non-stop,"7,487"
2,Feb 04,AirAsia,Bangalore,Delhi,11:20,14:05,02h 45m,BLR--->DEL,non-stop,"7,489"
3,Feb 04,Vistara,Bangalore,Delhi,07:00,09:40,02h 40m,BLR--->DEL,non-stop,"7,489"
4,Feb 04,Vistara,Bangalore,Delhi,08:00,10:40,02h 40m,BLR--->DEL,non-stop,"7,489"
...,...,...,...,...,...,...,...,...,...,...
8957,Mar 02,SpiceJet,Bangalore,Delhi,09:20,19:30,10h 10m,BLR--->JLR,1-stop,
8958,Mar 02,SpiceJet,Bangalore,Delhi,05:45,17:45,12h 00m,BLR--->GOI,1-stop,"6,118"
8959,Mar 02,SpiceJet,Bangalore,Delhi,05:45,22:10,16h 25m,BLR--->GOI,1-stop,
8960,Mar 02,SpiceJet,Bangalore,Delhi,14:05,16:35,26h 30m,BLR--->SAG,1-stop,"6,118"
8961,Mar 02,GO FIRST,Bangalore,Delhi,15:45,20:20,04h 35m,BLR--->GOI,1-stop,

In [30]:
driver.get('https://flight.easemytrip.com/FlightList/Index?srch=BOM-Mumbai-India|CCU-Kolkata-India|29/01/2022&px=1-0-0&cbn=0&ar=undefined&isow=true&isdm=true&lng=&CouponCode=&ompAff=&bc=&ISWL=')



time.sleep(3)

In [31]:

Airline =[]
Dep_time =[]
Arr_time =[]
Durtion =[]
Route =[]
Source =[]
Destination =[]
Stops =[]
Price =[]
Date =[]

In [32]:
for i in range(45):
    heading =driver.find_element_by_xpath('//*[@id="jssor_1"]/div/div/div/div/div[2]/div[7]/div[1]/div[1]/div[1]')
    heading.click()
    time.sleep(6)
    
    

    #Airline
    for i in driver.find_elements_by_xpath("//*[@id='ResultDiv']/div/div/div/div/div/div/div/div/div/span[1]"):
        Airline.append(i.text)


    #departure time
    for i in driver.find_elements_by_xpath('//*[@id="ResultDiv"]/div/div/div/div/div/div/div[2]/span[1]'):
        Dep_time.append(i.text)



    #arrival time
    for i in driver.find_elements_by_xpath('//*[@id="ResultDiv"]/div/div/div/div/div/div/div[4]/span[1]'):
        Arr_time.append(i.text)


    #duration in hours
    for i in driver.find_elements_by_xpath('//*[@id="ResultDiv"]/div/div/div/div/div/div/div[3]/span[1]'):
        Durtion.append(i.text)


    #route 
    count=0

    for i in driver.find_elements_by_xpath('//*[@id="ResultDiv"]/div/div/div/div/div/div/div[3]/span[2]'):
        Stops.append(i.text)
        detail =driver.find_element_by_xpath(f"//*[@id='{count}']")
        detail.click()
        route1 =driver.find_element_by_xpath(f'//*[@id="fd{count}"]/div/div[2]/div[1]/span[1]/span[1]')
        route2 =driver.find_element_by_xpath(f'//*[@id="fd{count}"]/div/div[2]/div[1]/span[1]/span[2]')
        """try:
            route3 =driver.find_element_by_xpath(f'//*[@id="fd{count}"]/div/div[2]/div[2]/span[1]/span[2]')
        except:
            break"""

        str1 = '--->'

        via =route1.text + str1
        route4= via + route2.text
        # route5 =route4 + str1 
        # route6 =route5 + route3.text
        Route.append(route4)


        count +=1

    #source
    for i in driver.find_elements_by_xpath('//*[@id="ResultDiv"]/div/div/div/div/div/div[1]/div[2]/span[2]'):
        Source.append(i.text)
    #destination
    for i in driver.find_elements_by_xpath('//*[@id="ResultDiv"]/div/div/div/div/div/div/div[4]/span[2]'):
        Destination.append(i.text)
    #price    
    for i in driver.find_elements_by_xpath('//*[@class="col-md-8 col-sm-8 col-xs-9 txt-r6-n ng-binding"]'):
        Price.append(i.text)
    #date
    i  = driver.find_elements_by_xpath('//*[@class="col-md-8 col-sm-8 col-xs-9 txt-r6-n ng-binding"]')
    for j in i:
        date1 =driver.find_element_by_xpath('//*[@id="jssor_1"]/div/div/div/div/div[2]/div[6]/div[1]/div[1]/div[1]') 
        Date.append(date1.text)

In [33]:
len(Airline) ,len(Dep_time),len(Arr_time),len(Durtion ),len(Route ),len(Source ),len(Destination),len(Stops),len(Price),len(Date)

(7054, 7054, 7054, 7054, 7054, 7054, 7054, 7054, 12017, 12017)

In [35]:
Price

['7,518',
 '7,412',
 '',
 '7,412',
 '',
 '7,413',
 '',
 '7,413',
 '',
 '7,412',
 '',
 '7,412',
 '',
 '7,412',
 '',
 '7,412',
 '',
 '7,412',
 '',
 '7,412',
 '',
 '7,412',
 '',
 '7,412',
 '',
 '7,412',
 '',
 '7,412',
 '',
 '7,412',
 '',
 '7,412',
 '',
 '7,412',
 '',
 '7,412',
 '',
 '7,412',
 '',
 '7,412',
 '',
 '7,833',
 '',
 '7,919',
 '',
 '8,883',
 '',
 '8,883',
 '',
 '8,883',
 '',
 '8,883',
 '',
 '10,058',
 '10,058',
 '10,058',
 '10,058',
 '10,058',
 '10,058',
 '10,058',
 '10,058',
 '10,058',
 '10,058',
 '9,723',
 '',
 '9,723',
 '',
 '9,828',
 '',
 '9,881',
 '',
 '10,143',
 '',
 '10,156',
 '',
 '10,616',
 '',
 '10,668',
 '',
 '10,668',
 '',
 '11,508',
 '',
 '11,508',
 '',
 '11,508',
 '',
 '11,508',
 '',
 '11,508',
 '',
 '11,508',
 '',
 '11,508',
 '',
 '11,508',
 '',
 '11,508',
 '',
 '11,508',
 '',
 '11,508',
 '',
 '11,508',
 '',
 '11,508',
 '',
 '11,508',
 '',
 '11,617',
 '',
 '11,717',
 '',
 '11,717',
 '',
 '11,717',
 '',
 '11,717',
 '',
 '11,717',
 '',
 '12,557',
 '12,557',
 '12,557',
 '12,557',
 '12,557',
 '12,557',
 '12,557',
 '12,557',
 '12,557',
 '12,557',
 '12,348',
 '',
 '12,348',
 '',
 '12,716',
 '',
 '13,176',
 '13,176',
 '13,176',
 '12,899',
 '',
 '12,899',
 '',
 '12,899',
 '',
 '13,191',
 '',
 '13,191',
 '',
 '13,926',
 '',
 '13,926',
 '',
 '13,926',
 '',
 '13,926',
 '',
 '14,002',
 '',
 '14,343',
 '',
 '14,343',
 '',
 '15,367',
 '',
 '17,073',
 '17,073',
 '17,073',
 '17,073',
 '17,073',
 '18,594',
 '20,328',
 '',
 '21,141',
 '',
 '25,001',
 '24,817',
 '',
 '7,413',
 '7,412',
 '',
 '7,412',
 '',
 '7,412',
 '',
 '7,412',
 '',
 '7,412',
 '',
 '7,412',
 '',
 '7,412',
 '',
 '7,412',
 '',
 '7,412',
 '',
 '7,412',
 '',
 '7,412',
 '',
 '7,412',
 '',
 '7,412',
 '',
 '7,412',
 '',
 '7,412',
 '',
 '7,412',
 '',
 '7,728',
 '',
 '8,253',
 '',
 '8,778',
 '8,778',
 '8,673',
 '',
 '8,883',
 '',
 '8,883',
 '',
 '9,093',
 '',
 '9,146',
 '',
 '9,146',
 '',
 '9,198',
 '',
 '9,398',
 '',
 '9,398',
 '',
 '9,513',
 '',
 '9,828',
 '',
 '10,458',
 '',
 '10,458',
 '',
 '10,616',
 '',
 '11,141',
 '',
 '11,508',
 '',
 '11,508',
 '',
 '11,521',
 '',
 '12,007',
 '',
 '12,007',
 '',
 '12,007',
 '',
 '12,007',
 '',
 '12,007',
 '',
 '12,007',
 '',
 '12,007',
 '',
 '12,007',
 '',
 '12,007',
 '',
 '12,007',
 '',
 '12,007',
 '',
 '12,032',
 '',
 '12,032',
 '',
 '12,032',
 '',
 '12,086',
 '',
 '12,086',
 '',
 '12,347',
 '',
 '12,347',
 '',
 '12,347',
 '',
 '12,347',
 '',
 '12,347',
 '',
 '12,347',
 '',
 '12,347',
 '',
 '12,347',
 '',
 '12,348',
 '',
 '12,348',
 '',
 '12,348',
 '',
 '12,611',
 '',
 '13,176',
 '13,251',
 '',
 '13,791',
 '',
 '14,343',
 '',
 '14,343',
 '',
 '14,400',
 '',
 '14,400',
 '',
 '14,400',
 '',
 '14,400',
 '',
 '14,400',
 '',
 '14,400',
 '',
 '14,400',
 '',
 '14,400',
 '',
 '14,556',
 '',
 '14,868',
 '',
 '14,868',
 '',
 '16,013',
 '',
 '16,013',
 '',
 '16,013',
 '',
 '16,013',
 '',
 '16,013',
 '',
 '16,311',
 '',
 '20,328',
 '',
 '21,273',
 '21,273',
 '21,273',
 '21,273',
 '21,247',
 '',
 '21,247',
 '',
 '22,323',
 '30,907',
 '',
 '34,083',
 '',
 '7,412',
 '',
 '7,412',
 '',
 '7,412',
 '',
 '7,412',
 '',
 '7,412',
 '',
 '7,412',
 '',
 '7,412',
 '',
 '7,412',
 '',
 '7,412',
 '',
 '7,412',
 '',
 '7,412',
 '',
 '7,412',
 '',
 '7,412',
 '',
 '7,412',
 '',
 '7,412',
 '',
 '7,412',
 '',
 '7,412',
 '',
 '7,412',
 '',
 '7,412',
 '',
 '7,412',
 '',
 '7,412',
 '',
 '7,412',
 '',
 '7,412',
 '',
 '7,412',
 '',
 '7,412',
 '',
 '7,412',
 '',
 '7,919',
 '',
 '7,919',
 '',
 '8,042',
 '',
 '8,936',
 '',
 '8,936',
 '',
 '9,146',
 '',
 '9,146',
 '',
 '9,146',
 '',
 '9,146',
 '',
 '9,526',
 '',
 '9,618',
 '',
 '9,723',
 '',
 '9,723',
 '',
 '9,828',
 '',
 '9,828',
 '',
 '10,668',
 '',
 '10,983',
 '',
 '11,456',
 '',
 '11,508',
 '',
 '11,508',
 '',
 '11,508',
 '',
 '11,666',
 '',
 '11,823',
 '',
 '11,881',
 '',
 '12,007',
 '',
 '12,007',
 '',
 '12,007',
 '',
 '12,663',
 '',
 '12,939',
 '',
 '12,939',
 '',
 '12,939',
 '',
 '12,939',
 '',
 '12,939',
 '',
 '12,939',
 '',
 '13,149',
 '',
 '13,713',
 '',
 '13,926',
 '',
 '13,926',
 '',
 '14,211',
 '',
 '15,367',
 '',
 '15,738',
 '15,738',
 '15,738',
 '15,738',
 '15,738',
 '15,738',
 '15,738',
 '15,738',
 '15,738',
 '15,738',
 '15,738',
 '15,393',
 '',
 '15,551',
 '',
 '16,485',
 '',
 '16,485',
 '',
 '18,333',
 '18,333',
 '18,333',
 '18,333',
 '20,328',
 '20,539',
 '',
 '26,208',
 '7,412',
 '',
 '7,412',
 '',
 '7,412',
 '',
 '7,412',
 '',
 '7,413',
 '',
 '7,413',
 '',
 '7,412',
 '',
 '7,412',
 '',
 '7,412',
 '',
 '7,412',
 '',
 '7,412',
 '',
 '7,412',
 '',
 '7,412',
 '',
 '7,412',
 '',
 '7,412',
 '',
 '7,412',
 '',
 '7,412',
 '',
 '7,412',
 '',
 '7,412',
 '',
 '7,412',
 '',
 '7,412',
 '',
 '7,412',
 '',
 '7,412',
 '',
 '7,412',
 '',
 '7,412',
 '',
 '7,412',
 '',
 '7,412',
 '',
 '7,412',
 '',
 '7,412',
 '',
 '7,412',
 '',
 '7,412',
 '',
 '7,412',
 '',
 '7,412',
 '',
 '7,412',
 '',
 '7,412',
 '',
 '7,412',
 '',
 '7,412',
 '',
 '7,413',
 '',
 '7,518',
 '',
 '7,919',
 '',
 '8,883',
 '',
 '9,146',
 '',
 '9,398',
 '',
 '9,526',
 '',
 '9,879',
 '9,879',
 '9,879',
 '9,879',
 '9,879',
 '9,879',
 '9,879',
 '9,879',
 '9,879',
 '9,879',
 '9,879',
 '9,879',
 '9,879',
 '9,879',
 '9,879',
 '9,879',
 '10,058',
 '10,058',
 '9,723',
 '',
 '9,723',
 '',
 '9,828',
 '',
 '9,828',
 '',
 '10,616',
 '',
 '10,668',
 '',
 '10,668',
 '',
 '10,668',
 '',
 '11,508',
 '',
 '11,508',
 '',
 '11,508',
 '',
 '11,508',
 '',
 '11,508',
 '',
 '11,508',
 '',
 '11,508',
 '',
 '11,508',
 '',
 '11,508',
 '',
 '11,508',
 '',
 '11,508',
 '',
 '11,508',
 '',
 '11,508',
 '',
 '11,508',
 '',
 '11,509',
 '',
 '11,717',
 '',
 '11,717',
 '',
 '11,719',
 '',
 '11,881',
 '',
 '11,928',
 '',
 '11,928',
 '',
 '11,928',
 '',
 '11,928',
 '',
 '12,347',
 '',
 '12,347',
 '',
 '12,347',
 '',
 '13,176',
 '12,899',
 '',
 '12,899',
 '',
 '12,899',
 '',
 '12,899',
 '',
 '12,899',
 '',
 '13,311',
 '13,083',
 '',
 '13,361',
 '',
 '13,371',
 '',
 '13,926',
 '',
 '13,926',
 '',
 '14,343',
 '14,343',
 '14,343',
 '14,343',
 '19,383',
 '20,328',
 '21,273',
 '21,273',
 '21,273',
 '21,378',
 '23,451',
 '',
 '24,886',
 '26,943',
 '27,249',
 '7,412',
 '7,518',
 '7,518',
 '7,518',
 '7,412',
 '',
 '7,412',
 '',
 '7,412',
 '',
 '7,413',
 '',
 '7,413',
 '',
 '7,413',
 '',
 '7,412',
 '',
 '7,412',
 '',
 '7,412',
 '',
 '7,412',
 '',
 '7,412',
 '',
 '7,412',
 '',
 '7,412',
 '',
 '7,412',
 '',
 '7,412',
 '',
 '7,412',
 '',
 '7,412',
 '',
 '7,412',
 '',
 '7,412',
 '',
 '7,412',
 '',
 '7,412',
 '',
 '7,412',
 '',
 '7,412',
 '',
 '7,412',
 '',
 '7,412',
 '',
 '7,412',
 '',
 '7,412',
 '',
 '7,412',
 '',
 '7,412',
 '',
 '7,412',
 '',
 '7,412',
 '',
 '7,412',
 '',
 '7,412',
 '',
 '7,412',
 '',
 '7,833',
 '',
 '7,833',
 '',
 '8,778',
 '',
 '8,883',
 '',
 '8,883',
 '',
 '8,883',
 '',
 '8,883',
 '',
 '9,146',
 '',
 '9,146',
 '',
 '9,618',
 '',
 '9,671',
 '',
 '10,058',
 '10,058',
 '10,058',
 '10,058',
 '10,058',
 '10,058',
 '10,058',
 '10,058',
 '9,723',
 '',
 '9,828',
 '',
 '9,828',
 '',
 '9,828',
 '',
 '10,127',
 '',
 '10,418',
 '',
 '10,826',
 '',
 '11,664',
 '11,664',
 '11,349',
 '',
 '11,349',
 '',
 '11,349',
 '',
 '11,349',
 '',
 '11,349',
 '',
 '11,349',
 '',
 '11,349',
 '',
 '11,349',
 '',
 '11,349',
 '',
 '11,349',
 '',
 '11,349',
 '',
 '11,349',
 '',
 '11,508',
 '',
 '11,508',
 '',
 '11,508',
 '',
 '11,508',
 '',
 '11,508',
 '',
 '11,508',
 '',
 '11,617',
 '',
 '11,617',
 '',
 '11,928',
 '',
 '11,928',
 '',
 '12,007',
 '',
 '12,007',
 '',
 '12,007',
 '',
 '12,007',
 '',
 '12,007',
 '',
 '12,007',
 '',
 '12,007',
 '',
 '12,007',
 '',
 '12,007',
 '',
 '12,007',
 '',
 '12,007',
 '',
 '13,371',
 '',
 '13,401',
 '',
 '13,401',
 '',
 '14,343',
 '14,343',
 '14,343',
 '14,657',
 '14,657',
 '14,400',
 '',
 '14,400',
 '',
 '15,918',
 '15,918',
 '16,758',
 '17,073',
 '17,073',
 '17,073',
 '17,073',
 '16,941',
 '',
 '18,858',
 '7,412',
 '7,412',
 '',
 '7,412',
 '',
 '7,412',
 '',
 '7,412',
 '',
 '7,412',
 '',
 '7,412',
 '',
 '7,412',
 '',
 '7,412',
 '',
 '7,412',
 '',
 '7,412',
 '',
 '7,412',
 '',
 '7,412',
 '',
 '7,412',
 '',
 '7,412',
 '',
 '7,412',
 '',
 '7,412',
 '',
 '7,412',
 '',
 '7,412',
 '',
 '7,412',
 '',
 '7,412',
 '',
 '7,412',
 '',
 '7,412',
 '',
 '7,412',
 '',
 '7,412',
 '',
 '7,412',
 '',
 '7,412',
 '',
 ...]

In [36]:
 df1 = pd.DataFrame({"Date":Date[0:7054],
                      "Airline" : Airline,
                     "Source":Source,
                     "Destination":Destination,
                       "Dep_time" : Dep_time,
                       "Arr_time" : Arr_time,
                       "Durtion" : Durtion,
                        "Route":Route,
                         "stop": Stops,
                       "price": Price[0:7054]
                       })
df1

,Date,Airline,Source,Destination,Dep_time,Arr_time,Durtion,Route,stop,price
0,Feb 03,Vistara,Mumbai,Kolkata,12:25,16:50,04h 25m,BOM--->CCU,1-stop,"7,518"
1,Feb 03,GO FIRST,Mumbai,Kolkata,05:00,07:30,02h 30m,BOM--->CCU,non-stop,"7,412"
2,Feb 03,GO FIRST,Mumbai,Kolkata,21:00,23:35,02h 35m,BOM--->CCU,non-stop,
3,Feb 03,Indigo,Mumbai,Kolkata,21:40,00:10,02h 30m,BOM--->CCU,non-stop,"7,412"
4,Feb 03,Indigo,Mumbai,Kolkata,23:00,01:30,02h 30m,BOM--->CCU,non-stop,
...,...,...,...,...,...,...,...,...,...,...
7049,Mar 02,SpiceJet,Mumbai,Kolkata,13:00,14:20,25h 20m,BOM--->IXB,1-stop,
7050,Mar 02,SpiceJet,Mumbai,Kolkata,13:50,17:45,27h 55m,BOM--->GWL,1-stop,"4,985"
7051,Mar 02,Indigo,Mumbai,Kolkata,13:55,22:55,09h 00m,BOM--->BBI,1-stop,
7052,Mar 02,Vistara,Mumbai,Kolkata,06:00,19:35,13h 35m,BOM--->IXC,1-stop,"5,070"
7053,Mar 02,Vistara,Mumbai,Kolkata,16:05,19:35,27h 30m,BOM--->IXC,1-stop,

In [37]:
driver.get('https://flight.easemytrip.com/FlightList/Index?srch=BOM-Mumbai-India|DEL-Delhi-India|01/02/2022&px=1-0-0&cbn=0&ar=undefined&isow=true&isdm=true&lng=&CouponCode=&ompAff=&bc=&ISWL=')



time.sleep(3)

In [38]:
Airline =[]
Dep_time =[]
Arr_time =[]
Durtion =[]
Route =[]
Source =[]
Destination =[]
Stops =[]
Price =[]
Date =[]

In [39]:
for i in range(45):
    heading =driver.find_element_by_xpath('//*[@id="jssor_1"]/div/div/div/div/div[2]/div[7]/div[1]/div[1]/div[1]')
    heading.click()
    time.sleep(6)
    
    

    #Airline
    for i in driver.find_elements_by_xpath("//*[@id='ResultDiv']/div/div/div/div/div/div/div/div/div/span[1]"):
        Airline.append(i.text)


    #departure time
    for i in driver.find_elements_by_xpath('//*[@id="ResultDiv"]/div/div/div/div/div/div/div[2]/span[1]'):
        Dep_time.append(i.text)



    #arrival time
    for i in driver.find_elements_by_xpath('//*[@id="ResultDiv"]/div/div/div/div/div/div/div[4]/span[1]'):
        Arr_time.append(i.text)


    #duration in hours
    for i in driver.find_elements_by_xpath('//*[@id="ResultDiv"]/div/div/div/div/div/div/div[3]/span[1]'):
        Durtion.append(i.text)


    #route 
    count=0

    for i in driver.find_elements_by_xpath('//*[@id="ResultDiv"]/div/div/div/div/div/div/div[3]/span[2]'):
        Stops.append(i.text)
        detail =driver.find_element_by_xpath(f"//*[@id='{count}']")
        detail.click()
        route1 =driver.find_element_by_xpath(f'//*[@id="fd{count}"]/div/div[2]/div[1]/span[1]/span[1]')
        route2 =driver.find_element_by_xpath(f'//*[@id="fd{count}"]/div/div[2]/div[1]/span[1]/span[2]')
        """try:
            route3 =driver.find_element_by_xpath(f'//*[@id="fd{count}"]/div/div[2]/div[2]/span[1]/span[2]')
        except:
            break"""

        str1 = '--->'

        via =route1.text + str1
        route4= via + route2.text
        # route5 =route4 + str1 
        # route6 =route5 + route3.text
        Route.append(route4)


        count +=1

    #source
    for i in driver.find_elements_by_xpath('//*[@id="ResultDiv"]/div/div/div/div/div/div[1]/div[2]/span[2]'):
        Source.append(i.text)
    #destination
    for i in driver.find_elements_by_xpath('//*[@id="ResultDiv"]/div/div/div/div/div/div/div[4]/span[2]'):
        Destination.append(i.text)
    #price    
    for i in driver.find_elements_by_xpath('//*[@class="col-md-8 col-sm-8 col-xs-9 txt-r6-n ng-binding"]'):
        Price.append(i.text)
    #date
    i  = driver.find_elements_by_xpath('//*[@class="col-md-8 col-sm-8 col-xs-9 txt-r6-n ng-binding"]')
    for j in i:
        date1 =driver.find_element_by_xpath('//*[@id="jssor_1"]/div/div/div/div/div[2]/div[6]/div[1]/div[1]/div[1]') 
        Date.append(date1.text)

In [40]:
len(Airline) ,len(Dep_time),len(Arr_time),len(Durtion ),len(Route ),len(Source ),len(Destination),len(Stops),len(Price),len(Date)

(8555, 8555, 8555, 8555, 8555, 8555, 8555, 8555, 14296, 14296)

In [41]:
Price

['5,942',
 '5,942',
 '5,942',
 '5,942',
 '5,942',
 '5,942',
 '5,942',
 '5,942',
 '5,942',
 '5,943',
 '5,943',
 '5,943',
 '5,943',
 '5,943',
 '5,943',
 '5,943',
 '5,943',
 '5,943',
 '5,943',
 '5,943',
 '',
 '5,943',
 '',
 '5,943',
 '',
 '5,943',
 '',
 '5,943',
 '',
 '5,943',
 '',
 '5,943',
 '',
 '5,943',
 '',
 '5,943',
 '',
 '5,943',
 '',
 '5,943',
 '',
 '5,943',
 '',
 '5,943',
 '',
 '5,942',
 '',
 '5,942',
 '',
 '5,942',
 '',
 '5,942',
 '',
 '5,942',
 '',
 '5,942',
 '',
 '5,942',
 '',
 '5,942',
 '',
 '5,942',
 '',
 '5,942',
 '',
 '5,942',
 '',
 '5,942',
 '',
 '5,942',
 '',
 '5,942',
 '',
 '5,942',
 '',
 '5,942',
 '',
 '5,942',
 '',
 '5,942',
 '',
 '5,942',
 '',
 '5,942',
 '',
 '5,942',
 '',
 '5,942',
 '',
 '5,942',
 '',
 '5,942',
 '',
 '5,942',
 '',
 '5,942',
 '',
 '5,942',
 '',
 '5,942',
 '',
 '5,942',
 '',
 '5,943',
 '',
 '5,943',
 '',
 '5,943',
 '',
 '6,153',
 '',
 '6,431',
 '',
 '8,873',
 '',
 '8,926',
 '',
 '9,356',
 '9,093',
 '',
 '9,828',
 '9,828',
 '9,881',
 '9,881',
 '9,933',
 '9,986',
 '9,986',
 '9,828',
 '',
 '9,828',
 '',
 '10,186',
 '9,849',
 '',
 '9,976',
 '',
 '10,563',
 '10,248',
 '',
 '10,616',
 '10,418',
 '',
 '10,418',
 '',
 '10,668',
 '',
 '11,088',
 '11,088',
 '11,113',
 '',
 '11,299',
 '',
 '11,508',
 '',
 '11,508',
 '',
 '11,508',
 '',
 '12,138',
 '12,138',
 '12,138',
 '12,138',
 '12,138',
 '12,138',
 '12,138',
 '12,138',
 '12,138',
 '12,138',
 '12,138',
 '12,138',
 '12,138',
 '12,138',
 '12,138',
 '11,888',
 '',
 '11,888',
 '',
 '12,033',
 '',
 '12,453',
 '12,138',
 '',
 '12,138',
 '',
 '12,138',
 '',
 '12,138',
 '',
 '12,138',
 '',
 '12,138',
 '',
 '12,138',
 '',
 '13,398',
 '',
 '14,028',
 '14,028',
 '14,028',
 '13,801',
 '',
 '13,801',
 '',
 '14,448',
 '14,107',
 '',
 '14,553',
 '14,553',
 '14,553',
 '14,973',
 '14,911',
 '',
 '15,393',
 '',
 '15,813',
 '15,708',
 '',
 '16,207',
 '',
 '16,233',
 '',
 '16,338',
 '',
 '16,474',
 '',
 '16,474',
 '',
 '17,178',
 '17,493',
 '17,703',
 '18,963',
 '19,173',
 '',
 '20,433',
 '',
 '22,008',
 '',
 '22,113',
 '',
 '23,268',
 '',
 '25,158',
 '',
 '26,981',
 '',
 '26,981',
 '',
 '5,942',
 '5,942',
 '5,942',
 '5,942',
 '5,942',
 '5,942',
 '5,942',
 '5,942',
 '5,943',
 '5,943',
 '5,943',
 '5,943',
 '5,943',
 '5,943',
 '5,943',
 '5,943',
 '5,943',
 '5,942',
 '',
 '5,943',
 '',
 '5,943',
 '',
 '5,943',
 '',
 '5,943',
 '',
 '5,943',
 '',
 '5,943',
 '',
 '5,943',
 '',
 '5,943',
 '',
 '5,943',
 '',
 '5,943',
 '',
 '5,943',
 '',
 '5,943',
 '',
 '5,943',
 '',
 '5,943',
 '',
 '5,942',
 '',
 '5,942',
 '',
 '5,942',
 '',
 '5,942',
 '',
 '5,942',
 '',
 '5,942',
 '',
 '5,942',
 '',
 '5,942',
 '',
 '5,942',
 '',
 '5,942',
 '',
 '5,942',
 '',
 '5,942',
 '',
 '5,942',
 '',
 '5,942',
 '',
 '5,942',
 '',
 '5,942',
 '',
 '5,942',
 '',
 '5,942',
 '',
 '5,942',
 '',
 '5,942',
 '',
 '5,942',
 '',
 '5,942',
 '',
 '5,942',
 '',
 '5,942',
 '',
 '5,942',
 '',
 '5,942',
 '',
 '5,943',
 '',
 '5,943',
 '',
 '5,943',
 '',
 '6,153',
 '',
 '6,449',
 '',
 '6,993',
 '7,408',
 '',
 '7,896',
 '',
 '8,883',
 '9,136',
 '9,136',
 '',
 '9,828',
 '9,828',
 '9,881',
 '9,881',
 '9,828',
 '',
 '9,828',
 '',
 '10,248',
 '',
 '10,418',
 '',
 '10,537',
 '',
 '10,983',
 '10,668',
 '',
 '11,613',
 '11,508',
 '',
 '12,138',
 '12,138',
 '12,138',
 '12,138',
 '12,138',
 '12,138',
 '12,138',
 '12,138',
 '12,138',
 '12,138',
 '12,138',
 '12,138',
 '12,138',
 '12,138',
 '12,138',
 '11,888',
 '',
 '11,888',
 '',
 '12,243',
 '12,033',
 '',
 '12,453',
 '12,453',
 '12,138',
 '',
 '12,138',
 '',
 '12,138',
 '',
 '12,506',
 '12,348',
 '',
 '12,768',
 '',
 '12,978',
 '',
 '13,398',
 '13,398',
 '13,503',
 '13,713',
 '13,766',
 '13,687',
 '',
 '13,801',
 '',
 '13,819',
 '',
 '13,819',
 '',
 '14,238',
 '14,343',
 '14,343',
 '',
 '15,131',
 '15,813',
 '15,813',
 '15,918',
 '15,682',
 '',
 '15,708',
 '',
 '15,708',
 '',
 '16,023',
 '',
 '16,233',
 '',
 '16,653',
 '21,273',
 '',
 '27,206',
 '5,943',
 '5,943',
 '5,943',
 '5,942',
 '5,942',
 '5,942',
 '5,942',
 '5,942',
 '5,942',
 '5,943',
 '5,943',
 '5,943',
 '5,943',
 '5,943',
 '5,943',
 '5,943',
 '5,943',
 '6,048',
 '5,942',
 '',
 '5,943',
 '',
 '5,943',
 '',
 '5,943',
 '',
 '5,943',
 '',
 '5,943',
 '',
 '5,943',
 '',
 '5,943',
 '',
 '5,943',
 '',
 '5,943',
 '',
 '5,943',
 '',
 '5,943',
 '',
 '5,943',
 '',
 '5,943',
 '',
 '5,943',
 '',
 '5,943',
 '',
 '5,942',
 '',
 '5,942',
 '',
 '5,942',
 '',
 '5,942',
 '',
 '5,942',
 '',
 '5,942',
 '',
 '5,942',
 '',
 '5,942',
 '',
 '5,942',
 '',
 '5,942',
 '',
 '5,942',
 '',
 '5,942',
 '',
 '5,942',
 '',
 '5,942',
 '',
 '5,942',
 '',
 '5,942',
 '',
 '5,942',
 '',
 '5,942',
 '',
 '5,942',
 '',
 '5,942',
 '',
 '5,942',
 '',
 '5,942',
 '',
 '5,942',
 '',
 '5,942',
 '',
 '5,943',
 '',
 '5,943',
 '',
 '5,943',
 '',
 '5,943',
 '',
 '6,449',
 '',
 '6,520',
 '',
 '7,728',
 '7,408',
 '',
 '7,896',
 '',
 '8,148',
 '',
 '8,541',
 '',
 '9,136',
 '8,988',
 '',
 '9,198',
 '',
 '9,828',
 '9,828',
 '9,828',
 '9,828',
 '9,828',
 '9,828',
 '9,828',
 '9,933',
 '9,933',
 '9,828',
 '',
 '9,976',
 '',
 '9,976',
 '',
 '10,563',
 '10,248',
 '',
 '10,248',
 '',
 '10,248',
 '',
 '10,248',
 '',
 '10,337',
 '',
 '10,418',
 '',
 '10,458',
 '',
 '10,869',
 '10,668',
 '',
 '11,193',
 '11,193',
 '11,403',
 '11,613',
 '11,613',
 '11,363',
 '',
 '11,508',
 '',
 '11,508',
 '',
 '11,508',
 '',
 '12,138',
 '12,138',
 '12,138',
 '12,138',
 '12,138',
 '12,138',
 '12,138',
 '12,138',
 '11,877',
 '',
 '11,877',
 '',
 '11,877',
 '',
 '11,877',
 '',
 '12,243',
 '12,243',
 '12,243',
 '12,243',
 '12,243',
 '12,453',
 '12,138',
 '',
 '12,138',
 '',
 '12,243',
 '',
 '12,663',
 '12,716',
 '12,716',
 '13,188',
 '12,978',
 '',
 '12,978',
 '',
 '12,978',
 '',
 '12,978',
 '',
 '12,978',
 '',
 '12,978',
 '',
 '12,978',
 '',
 '12,978',
 '',
 '13,398',
 '13,398',
 '13,503',
 '13,219',
 '',
 '13,534',
 '',
 '14,028',
 '14,028',
 '14,238',
 '14,029',
 '',
 '14,658',
 '',
 '15,393',
 '',
 '16,207',
 '',
 '18,123',
 '',
 '19,251',
 '',
 '21,903',
 '',
 '21,903',
 '',
 '21,903',
 '',
 '25,998',
 '26,943',
 '32,718',
 '5,943',
 '5,943',
 '5,943',
 '5,943',
 '5,942',
 '5,942',
 '5,942',
 '5,942',
 '5,942',
 '5,942',
 '5,942',
 '5,942',
 '5,942',
 '5,943',
 '5,943',
 '5,943',
 '5,943',
 '5,943',
 '5,943',
 '5,943',
 '5,943',
 '5,943',
 '',
 '5,943',
 '',
 '5,943',
 '',
 '5,943',
 '',
 '5,943',
 '',
 '5,943',
 '',
 '5,943',
 '',
 '5,943',
 '',
 '5,943',
 '',
 '5,943',
 '',
 '5,943',
 '',
 '5,943',
 '',
 '5,943',
 '',
 '5,943',
 '',
 '5,942',
 '',
 '5,942',
 '',
 '5,942',
 '',
 '5,942',
 '',
 '5,942',
 '',
 '5,942',
 '',
 '5,942',
 '',
 '5,942',
 '',
 '5,942',
 '',
 '5,942',
 '',
 '5,942',
 '',
 '5,942',
 '',
 '5,942',
 '',
 '5,942',
 '',
 '5,942',
 '',
 '5,942',
 '',
 '5,942',
 '',
 '5,942',
 '',
 '5,942',
 '',
 '5,942',
 '',
 '5,942',
 '',
 '5,942',
 '',
 '5,942',
 '',
 '5,942',
 '',
 '5,942',
 '',
 '5,942',
 '',
 '5,942',
 '',
 '5,942',
 '',
 '5,942',
 '',
 '5,942',
 '',
 '5,943',
 '',
 '5,943',
 '',
 '5,943',
 '',
 '6,048',
 '',
 '6,431',
 '',
 '7,518',
 '7,518',
 '8,358',
 '8,096',
 '',
 '8,148',
 '',
 '8,296',
 '',
 '8,296',
 '',
 '9,136',
 '',
 '9,828',
 '9,828',
 '9,828',
 '9,828',
 '9,828',
 '9,828',
 '9,828',
 '9,828',
 '9,828',
 '9,828',
 '9,828',
 '',
 '9,828',
 '',
 '9,828',
 '',
 '9,853',
 '',
 '9,933',
 '',
 '9,976',
 '',
 '9,976',
 '',
 '10,143',
 '',
 '10,563',
 '10,337',
 '',
 '10,721',
 '10,418',
 '',
 '10,418',
 '',
 '10,458',
 '',
 '10,563',
 '',
 '10,563',
 '',
 '11,193',
 '11,193',
 '11,193',
 '11,299',
 '',
 '11,403',
 '',
 '11,403',
 '',
 '11,508',
 '',
 '11,508',
 '',
 '11,508',
 '',
 '11,508',
 '',
 '12,138',
 '12,138',
 '12,138',
 '12,138',
 '12,138',
 '12,138',
 '12,138',
 '12,138',
 '12,138',
 '12,138',
 '12,138',
 '12,138',
 '12,138',
 '12,138',
 '12,138',
 '11,888',
 '',
 '11,888',
 '',
 '12,138',
 '',
 '12,138',
 '',
 '12,138',
 '',
 '12,138',
 '',
 '12,138',
 '',
 '12,321',
 '',
 '12,663',
 '',
 '12,663',
 '',
 '12,663',
 '',
 '12,978',
 '',
 '12,978',
 '',
 '12,978',
 '',
 '12,978',
 '',
 '12,978',
 '',
 '13,398',
 '13,398',
 '13,398',
 '13,398',
 '',
 '13,801',
 '',
 '13,801',
 '',
 '14,553',
 '14,658',
 '14,658',
 '14,973',
 '14,658',
 '',
 '14,868',
 '',
 '15,393',
 '',
 '16,233',
 '',
 '20,643',
 '20,853',
 '21,903',
 '',
 '5,943',
 '5,943',
 '5,943',
 '5,942',
 '5,942',
 '5,942',
 '5,942',
 '5,942',
 '5,942',
 '5,942',
 '5,942',
 '5,942',
 '5,943',
 '5,943',
 '5,943',
 '5,943',
 '5,943',
 '5,943',
 '5,943',
 '5,943',
 '5,943',
 '5,943',
 '5,943',
 '',
 '5,943',
 '',
 '5,943',
 '',
 '5,943',
 '',
 '5,943',
 '',
 '5,943',
 ...]

In [42]:
df2 = pd.DataFrame({"Date":Date[0:8555],
                      "Airline" : Airline,
                     "Source":Source,
                     "Destination":Destination,
                       "Dep_time" : Dep_time,
                       "Arr_time" : Arr_time,
                       "Durtion" : Durtion,
                        "Route":Route,
                         "stop": Stops,
                       "price": Price[0:8555]
                       })
df2

,Date,Airline,Source,Destination,Dep_time,Arr_time,Durtion,Route,stop,price
0,Feb 04,GO FIRST,Mumbai,Delhi,06:00,08:10,02h 10m,BOM--->DEL,non-stop,"5,942"
1,Feb 04,GO FIRST,Mumbai,Delhi,08:00,10:10,02h 10m,BOM--->DEL,non-stop,"5,942"
2,Feb 04,GO FIRST,Mumbai,Delhi,18:00,20:10,02h 10m,BOM--->DEL,non-stop,"5,942"
3,Feb 04,GO FIRST,Mumbai,Delhi,20:15,22:25,02h 10m,BOM--->DEL,non-stop,"5,942"
4,Feb 04,GO FIRST,Mumbai,Delhi,22:40,00:50,02h 10m,BOM--->DEL,non-stop,"5,942"
...,...,...,...,...,...,...,...,...,...,...
8550,Mar 04,Air India,Mumbai,Delhi,05:05,16:45,11h 40m,BOM--->GOI,1-stop,
8551,Mar 04,GO FIRST,Mumbai,Delhi,15:20,20:20,05h 00m,BOM--->GOI,1-stop,"2,339"
8552,Mar 04,GO FIRST,Mumbai,Delhi,11:30,20:20,08h 50m,BOM--->GOI,1-stop,
8553,Mar 04,GO FIRST,Mumbai,Delhi,09:00,20:20,11h 20m,BOM--->GOI,1-stop,"2,339"
8554,Mar 04,Vistara,Mumbai,Delhi,11:25,17:05,05h 40m,BOM--->GOI,1-stop,

In [46]:
driver.get('https://flight.easemytrip.com/FlightList/Index?srch=HYD-Hyderabad-India|CCU-Kolkata-India|01/02/2022&px=1-0-0&cbn=0&ar=undefined&isow=true&isdm=true&lng=&CouponCode=&ompAff=&bc=&ISWL=')



time.sleep(3)

In [47]:
Airline =[]
Dep_time =[]
Arr_time =[]
Durtion =[]
Route =[]
Source =[]
Destination =[]
Stops =[]
Price =[]
Date =[]

In [48]:
for i in range(45):
    heading =driver.find_element_by_xpath('//*[@id="jssor_1"]/div/div/div/div/div[2]/div[7]/div[1]/div[1]/div[1]')
    heading.click()
    time.sleep(6)
    
    

    #Airline
    for i in driver.find_elements_by_xpath("//*[@id='ResultDiv']/div/div/div/div/div/div/div/div/div/span[1]"):
        Airline.append(i.text)


    #departure time
    for i in driver.find_elements_by_xpath('//*[@id="ResultDiv"]/div/div/div/div/div/div/div[2]/span[1]'):
        Dep_time.append(i.text)



    #arrival time
    for i in driver.find_elements_by_xpath('//*[@id="ResultDiv"]/div/div/div/div/div/div/div[4]/span[1]'):
        Arr_time.append(i.text)


    #duration in hours
    for i in driver.find_elements_by_xpath('//*[@id="ResultDiv"]/div/div/div/div/div/div/div[3]/span[1]'):
        Durtion.append(i.text)


    #route 
    count=0

    for i in driver.find_elements_by_xpath('//*[@id="ResultDiv"]/div/div/div/div/div/div/div[3]/span[2]'):
        Stops.append(i.text)
        detail =driver.find_element_by_xpath(f"//*[@id='{count}']")
        detail.click()
        route1 =driver.find_element_by_xpath(f'//*[@id="fd{count}"]/div/div[2]/div[1]/span[1]/span[1]')
        route2 =driver.find_element_by_xpath(f'//*[@id="fd{count}"]/div/div[2]/div[1]/span[1]/span[2]')
        """try:
            route3 =driver.find_element_by_xpath(f'//*[@id="fd{count}"]/div/div[2]/div[2]/span[1]/span[2]')
        except:
            break"""

        str1 = '--->'

        via =route1.text + str1
        route4= via + route2.text
        # route5 =route4 + str1 
        # route6 =route5 + route3.text
        Route.append(route4)


        count +=1

    #source
    for i in driver.find_elements_by_xpath('//*[@id="ResultDiv"]/div/div/div/div/div/div[1]/div[2]/span[2]'):
        Source.append(i.text)
    #destination
    for i in driver.find_elements_by_xpath('//*[@id="ResultDiv"]/div/div/div/div/div/div/div[4]/span[2]'):
        Destination.append(i.text)
    #price    
    for i in driver.find_elements_by_xpath('//*[@class="col-md-8 col-sm-8 col-xs-9 txt-r6-n ng-binding"]'):
        Price.append(i.text)
    #date
    i  = driver.find_elements_by_xpath('//*[@class="col-md-8 col-sm-8 col-xs-9 txt-r6-n ng-binding"]')
    for j in i:
        date1 =driver.find_element_by_xpath('//*[@id="jssor_1"]/div/div/div/div/div[2]/div[6]/div[1]/div[1]/div[1]') 
        Date.append(date1.text)

In [49]:
len(Airline) ,len(Dep_time),len(Arr_time),len(Durtion ),len(Route ),len(Source ),len(Destination),len(Stops),len(Price),len(Date)

(4215, 4215, 4215, 4215, 4215, 4215, 4215, 4215, 6760, 6760)

In [50]:
df3 = pd.DataFrame({"Date":Date[0:4215],
                      "Airline" : Airline,
                     "Source":Source,
                     "Destination":Destination,
                       "Dep_time" : Dep_time,
                       "Arr_time" : Arr_time,
                       "Durtion" : Durtion,
                        "Route":Route,
                         "stop": Stops,
                       "price": Price[0:4215]
                       })
df3

,Date,Airline,Source,Destination,Dep_time,Arr_time,Durtion,Route,stop,price
0,Feb 04,GO FIRST,Hyderabad,Kolkata,06:05,07:55,01h 50m,HYD--->CCU,non-stop,"5,292"
1,Feb 04,GO FIRST,Hyderabad,Kolkata,10:35,12:30,01h 55m,HYD--->CCU,non-stop,
2,Feb 04,Indigo,Hyderabad,Kolkata,17:15,19:15,02h 00m,HYD--->CCU,non-stop,"5,292"
3,Feb 04,Indigo,Hyderabad,Kolkata,20:35,22:40,02h 05m,HYD--->CCU,non-stop,
4,Feb 04,SpiceJet,Hyderabad,Kolkata,16:10,19:35,03h 25m,HYD--->VTZ,1-stop,"5,293"
...,...,...,...,...,...,...,...,...,...,...
4210,Mar 05,SpiceJet,Hyderabad,Kolkata,16:50,17:55,25h 05m,HYD--->JRG,1-stop,
4211,Mar 05,Vistara,Hyderabad,Kolkata,13:25,19:35,06h 10m,HYD--->DEL,1-stop,"2,393"
4212,Mar 05,Vistara,Hyderabad,Kolkata,10:20,19:35,09h 15m,HYD--->DEL,1-stop,
4213,Mar 05,Vistara,Hyderabad,Kolkata,06:50,19:35,12h 45m,HYD--->DEL,1-stop,"2,395"
4214,Mar 05,Vistara,Hyderabad,Kolkata,11:00,19:35,08h 35m,HYD--->IXC,1-stop,

In [51]:
df4 = pd.concat([df1,df2,df3,df], ignore_index=True)
df4

,Date,Airline,Source,Destination,Dep_time,Arr_time,Durtion,Route,stop,price
0,Feb 03,Vistara,Mumbai,Kolkata,12:25,16:50,04h 25m,BOM--->CCU,1-stop,"7,518"
1,Feb 03,GO FIRST,Mumbai,Kolkata,05:00,07:30,02h 30m,BOM--->CCU,non-stop,"7,412"
2,Feb 03,GO FIRST,Mumbai,Kolkata,21:00,23:35,02h 35m,BOM--->CCU,non-stop,
3,Feb 03,Indigo,Mumbai,Kolkata,21:40,00:10,02h 30m,BOM--->CCU,non-stop,"7,412"
4,Feb 03,Indigo,Mumbai,Kolkata,23:00,01:30,02h 30m,BOM--->CCU,non-stop,
...,...,...,...,...,...,...,...,...,...,...
28781,Mar 02,SpiceJet,Bangalore,Delhi,09:20,19:30,10h 10m,BLR--->JLR,1-stop,
28782,Mar 02,SpiceJet,Bangalore,Delhi,05:45,17:45,12h 00m,BLR--->GOI,1-stop,"6,118"
28783,Mar 02,SpiceJet,Bangalore,Delhi,05:45,22:10,16h 25m,BLR--->GOI,1-stop,
28784,Mar 02,SpiceJet,Bangalore,Delhi,14:05,16:35,26h 30m,BLR--->SAG,1-stop,"6,118"
28785,Mar 02,GO FIRST,Bangalore,Delhi,15:45,20:20,04h 35m,BLR--->GOI,1-stop,

In [52]:
# save data in excel format
df4.to_excel("flightprice_data.xlsx")